/**
 * LenderPortal — public-facing credit report page for lenders.
 *
 * Two entry points:
 *   1. /verify/:attestationId  — direct from a customer's share link (auto-loads report)
 *   2. /lender               — manual lookup form for lenders
 */
import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import api from '../api/client';
import '../styles/credit.css';

const BAND_LABELS = ['', 'Insufficient', 'Thin', 'Moderate', 'Good', 'Excellent'];
const BAND_COLORS = ['', '#DC2626', '#D97706', '#D97706', '#059669', '#047857'];
const BAND_BG     = ['', '#FEF2F2', '#FFFBEB', '#FFFBEB', '#F0FDF4', '#ECFDF5'];

const SCORE_FACTORS = [
  { key: 'consistency', label: 'Payment Consistency',   weight: '30%', desc: 'Regularity of transactions month over month' },
  { key: 'recency',     label: 'Recency of Activity',   weight: '25%', desc: 'How recently the applicant transacted' },
  { key: 'depth',       label: 'History Depth',         weight: '20%', desc: 'Length of the verifiable transaction record' },
  { key: 'diversity',   label: 'Merchant Diversity',    weight: '15%', desc: 'Breadth of spending across different merchants' },
  { key: 'volumeTrend', label: 'Volume Trend',          weight: '10%', desc: 'Direction of spending over the past six months' },
];

const SPEND_LABELS = {
  low:       'Below AED 2,000 / month',
  medium:    'AED 2,000 – 10,000 / month',
  high:      'AED 10,000 – 50,000 / month',
  very_high: 'Above AED 50,000 / month',
};

const REGULATORY_DISCLAIMER = `This document is a SafiScore Alternative Data Attestation generated by the SafiPoints platform. It is based solely on anonymised retail point-of-sale transaction activity recorded within the SafiPoints loyalty network and does not constitute a credit bureau report. It is not issued by, affiliated with, or endorsed by the Al Etihad Credit Bureau (AECB), the Central Bank of the UAE, the Abu Dhabi Global Market (ADGM), or the Dubai International Financial Centre (DIFC). This attestation is intended solely as a supplementary credit signal for thin-file applicants, including expatriates who may lack a formal UAE credit history. Lending decisions must not be made on the basis of this attestation alone. All credit decisions remain the sole responsibility of the lending institution.`;

function ScoreBadge({ band }) {
  return (
    <div className="cr-score-badge" style={{ background: BAND_BG[band], borderColor: BAND_COLORS[band] }}>
      <div className="cr-score-band-number" style={{ color: BAND_COLORS[band] }}>{band}</div>
      <div className="cr-score-band-label" style={{ color: BAND_COLORS[band] }}>{BAND_LABELS[band]}</div>
      <div className="cr-score-band-scale">out of 5</div>
    </div>
  );
}

function FactorBar({ label, value, weight, desc }) {
  const tier = value >= 70 ? 'strong' : value >= 40 ? 'moderate' : 'weak';
  const barColor = tier === 'strong' ? '#059669' : tier === 'moderate' ? '#D97706' : '#DC2626';
  return (
    <div className="cr-factor-row">
      <div className="cr-factor-meta">
        <span className="cr-factor-label">{label}</span>
        <span className="cr-factor-weight">{weight}</span>
      </div>
      <div className="cr-factor-desc">{desc}</div>
      <div className="cr-factor-bar-wrap">
        <div className="cr-factor-bar-track">
          <div className="cr-factor-bar-fill" style={{ width: `${value || 0}%`, background: barColor }} />
        </div>
        <span className="cr-factor-score" style={{ color: barColor }}>{value ?? '—'}</span>
      </div>
    </div>
  );
}

function InvalidReport({ result }) {
  return (
    <div className="cr-invalid">
      <div className="cr-invalid-icon">✗</div>
      <div className="cr-invalid-title">Attestation Invalid</div>
      <p className="cr-invalid-body">
        {result.reason}
        {result.expiredAt && ` — expired ${new Date(result.expiredAt).toLocaleDateString('en-AE', { day: 'numeric', month: 'long', year: 'numeric' })}.`}
        {result.revokedAt && ` — revoked by the applicant on ${new Date(result.revokedAt).toLocaleDateString('en-AE', { day: 'numeric', month: 'long', year: 'numeric' })}.`}
      </p>
      <p className="cr-invalid-hint">Ask the applicant to generate a new signed attestation via the SafiPoints app.</p>
    </div>
  );
}

function CreditReport({ attestation }) {
  const band     = attestation.scoreBand;
  const breakdown = attestation.scoreBreakdown || {};
  const issued   = new Date(attestation.issuedAt);
  const expires  = new Date(attestation.expiresAt);
  const fmt      = d => d.toLocaleDateString('en-AE', { day: 'numeric', month: 'long', year: 'numeric' });
  const spendLabel = SPEND_LABELS[attestation.spendBand] || attestation.spendBand || 'Not disclosed';

  return (
    <div className="cr-report" id="cr-printable">

      {/* ── Report header ──────────────────────────────────────────── */}
      <div className="cr-report-header">
        <div className="cr-report-header-left">
          <div className="cr-report-wordmark">SafiScore</div>
          <div className="cr-report-type">Alternative Data Credit Attestation</div>
        </div>
        <div className="cr-report-header-right">
          <div className="cr-report-status-verified">
            <span className="cr-status-dot" />
            Cryptographically Verified
          </div>
        </div>
      </div>

      {/* ── Subject + metadata ─────────────────────────────────────── */}
      <div className="cr-section cr-meta-grid">
        <div>
          <div className="cr-field-label">Subject Reference</div>
          <div className="cr-field-value cr-mono">{attestation.subjectRef}</div>
        </div>
        <div>
          <div className="cr-field-label">Prepared For</div>
          <div className="cr-field-value">{attestation.lenderName || attestation.lenderIdentifier}</div>
        </div>
        <div>
          <div className="cr-field-label">Issue Date</div>
          <div className="cr-field-value">{fmt(issued)}</div>
        </div>
        <div>
          <div className="cr-field-label">Valid Until</div>
          <div className="cr-field-value">{fmt(expires)}</div>
        </div>
      </div>

      <div className="cr-divider" />

      {/* ── Score ─────────────────────────────────────────────────── */}
      <div className="cr-section cr-score-section">
        <div className="cr-score-left">
          <ScoreBadge band={band} />
        </div>
        <div className="cr-score-right">
          <div className="cr-score-headline">{BAND_LABELS[band]} Credit Signal</div>
          <div className="cr-score-overall">
            Composite score: <strong>{breakdown.overall ?? '—'} / 100</strong>
          </div>
          {attestation.scoreNarrative?.summary && (
            <p className="cr-score-narrative">{attestation.scoreNarrative.summary}</p>
          )}
        </div>
      </div>

      <div className="cr-divider" />

      {/* ── Key indicators ────────────────────────────────────────── */}
      <div className="cr-section">
        <div className="cr-section-title">Key Indicators</div>
        <div className="cr-indicators-grid">
          {[
            ['Transaction History', `${attestation.monthsOfHistory ?? '—'} months`],
            ['Merchant Diversity', `${attestation.merchantDiversity ?? '—'} merchants`],
            ['Estimated Spend Band', spendLabel],
            ['Data Freshness', attestation.freshnessScore != null ? `${attestation.freshnessScore} days since last transaction` : 'Unknown'],
          ].map(([label, value]) => (
            <div key={label} className="cr-indicator-box">
              <div className="cr-indicator-label">{label}</div>
              <div className="cr-indicator-value">{value}</div>
            </div>
          ))}
        </div>
      </div>

      <div className="cr-divider" />

      {/* ── Score factors ─────────────────────────────────────────── */}
      <div className="cr-section">
        <div className="cr-section-title">Score Factor Analysis</div>
        <div className="cr-factors-list">
          {SCORE_FACTORS.map(f => (
            <FactorBar
              key={f.key}
              label={f.label}
              weight={f.weight}
              desc={f.desc}
              value={breakdown[f.key]}
            />
          ))}
        </div>
        {attestation.scoreNarrative?.signals?.length > 0 && (
          <div className="cr-signals-list">
            <div className="cr-signals-title">Analyst Notes</div>
            {attestation.scoreNarrative.signals.map((s, i) => (
              <div key={i} className="cr-signal-row">
                <span className="cr-signal-bullet">–</span>
                <span className="cr-signal-text">{s}</span>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="cr-divider" />

      {/* ── Cryptographic integrity ───────────────────────────────── */}
      <div className="cr-section">
        <div className="cr-section-title">Attestation Integrity</div>
        <div className="cr-integrity-grid">
          <div>
            <div className="cr-field-label">Attestation ID</div>
            <div className="cr-field-value cr-mono cr-hash">{attestation.attestationId}</div>
          </div>
          <div>
            <div className="cr-field-label">Signature Hash (HMAC-SHA256)</div>
            <div className="cr-field-value cr-mono cr-hash">{attestation.proofHash}</div>
          </div>
        </div>
        <p className="cr-integrity-note">
          The signature hash cryptographically binds this attestation to the applicant's on-chain
          transaction record on the XRP Ledger. Any modification invalidates the signature.
        </p>
      </div>

      <div className="cr-divider" />

      {/* ── Regulatory disclaimer ─────────────────────────────────── */}
      <div className="cr-disclaimer">
        <div className="cr-disclaimer-title">Regulatory Disclaimer</div>
        <p className="cr-disclaimer-body">{REGULATORY_DISCLAIMER}</p>
      </div>

      {/* ── Print button ─────────────────────────────────────────── */}
      <div className="cr-print-row no-print">
        <button className="sp-btn sp-btn-ghost cr-print-btn" onClick={() => window.print()}>
          Print / Save as PDF
        </button>
      </div>

    </div>
  );
}

export default function LenderPortal() {
  const { attestationId: urlId } = useParams();

  const [inputId, setInputId] = useState(urlId || '');
  const [result, setResult]   = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError]     = useState(null);

  useEffect(() => {
    if (urlId && /^[a-f0-9]{64}$/.test(urlId)) {
      verify(urlId);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [urlId]);

  const verify = async (id) => {
    const cleaned = (id || inputId).trim();
    if (!cleaned) return;
    if (!/^[a-f0-9]{64}$/.test(cleaned)) {
      setError('Invalid attestation ID. It must be a 64-character hex string.');
      return;
    }
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const res = await api.get(`/safiscore/verify/${cleaned}`);
      setResult(res.data);
    } catch (err) {
      if (err.response?.status === 404) {
        setResult({ valid: false, reason: 'Attestation not found' });
      } else {
        setError('Verification service error. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    verify(inputId);
  };

  // When arriving via a share link and the report is loaded, show only the report
  if (result?.valid) {
    return (
      <div style={{ maxWidth: 760, margin: '0 auto', padding: '24px 16px' }}>
        <CreditReport attestation={result.attestation} />
      </div>
    );
  }

  return (
    <div style={{ maxWidth: 600, margin: '0 auto', padding: '24px 16px' }}>
      {/* ── Hero ─────────────────────────────────────────────────────── */}
      <div className="ss-verify-hero">
        <div className="ss-verify-title">SafiScore Lender Portal</div>
        <div className="ss-verify-subtitle">
          Verify an applicant's signed credit attestation. No phone calls, no paperwork.
        </div>
      </div>

      {/* ── Lookup form ──────────────────────────────────────────────── */}
      <div className="sp-card" style={{ marginBottom: 20 }}>
        <div className="sp-section-label" style={{ marginBottom: 12 }}>Load a credit report</div>
        <form onSubmit={handleSubmit}>
          <div className="sp-form-group">
            <label className="sp-label">Attestation ID</label>
            <input
              className="sp-input"
              type="text"
              placeholder="64-character hex ID from the applicant's share link"
              value={inputId}
              onChange={e => setInputId(e.target.value)}
              style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}
              required
            />
          </div>
          {error && (
            <p style={{ fontSize: 13, color: 'var(--danger)', marginTop: 8 }}>{error}</p>
          )}
          <button
            type="submit"
            className="sp-btn sp-btn-primary"
            style={{ width: '100%', marginTop: 16 }}
            disabled={loading}
          >
            {loading ? 'Loading report…' : 'Load credit report'}
          </button>
        </form>
      </div>

      {/* ── Invalid result ────────────────────────────────────────────── */}
      {result && !result.valid && <InvalidReport result={result} />}

      {/* ── How to use ───────────────────────────────────────────────── */}
      {!result && (
        <div className="sp-card">
          <div className="sp-section-label" style={{ marginBottom: 12 }}>How to use</div>
          {[
            ['1', 'Request a SafiScore signed attestation from your loan applicant.'],
            ['2', 'The applicant generates a share link via the SafiPoints app and sends it to you.'],
            ['3', 'Paste the 64-character attestation ID above and click Load credit report.'],
            ['4', 'Review the full credit report. No raw transaction data is disclosed.'],
          ].map(([num, text]) => (
            <div key={num} style={{ display: 'flex', gap: 12, marginBottom: 12 }}>
              <div style={{
                width: 24, height: 24, borderRadius: '50%',
                background: 'var(--navy)', color: 'white',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 12, fontWeight: 800, flexShrink: 0,
              }}>
                {num}
              </div>
              <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{text}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}


